

#ifndef DEV_CONF_PB_H__
#define DEV_CONF_PB_H__





typedef enum {

    // System
    DEV_CONF_SYSTEM_MODULE = 0x01, //R
    DEV_CONF_SYSTEM_FIRMWARE, //R
    DEV_CONF_SYSTEM_IMEI, //R
    DEV_CONF_SYSTEM_ICCID, //R
    DEV_CONF_SYSTEM_MAC, //R
    DEV_CONF_SYSTEM_SETTINGTIME, //R
    DEV_CONF_SYSTEM_RUNTIME, //R
    DEV_CONF_SYSTEM_FIRMWARE_INFO, //R
    DEV_CONF_SYSTEM_INIT_MILEAGE, //09
    DEV_CONF_SYSTEM_MODE, //RW 0xa
    DEV_CONF_SYSTEM_ALARMCLOCK, //RW 0x0b
    DEV_CONF_SYSTEM_NO_DISTURB, //0x0c
    DEV_CONF_SYSTEM_PASSWORD, //0x0d
    DEV_CONF_SYSTEM_TIMEZONE, //0x0e
    DEV_CONF_SYSTEM_ENABLE_CONTROL, //0x0F
    DEV_CONF_SYSTEM_RING_TONE_VOLUME, //0x10
    DEV_CONF_SYSTEM_MIC_VOLUME, //0X11
    DEV_CONF_SYSTEM_SPEAKER_VOLUME, //0X12
    DEV_CONF_SYSTEM_DEVICE_NAME, //0x13
    DEV_CONF_SYSTEM_BATTERY, //0X14
    DEV_CONF_SYSTEM_BLE_LOC, //0X15 only for docking station
    DEV_CONF_SYSTEM_BLE_WHITELIST, //0X16
    DEV_CONF_SYSTEM_GPS_URL, //0X17
    DEV_CONF_SYSTEM_WIFILBS_URL, //0X18
    DEV_CONF_SYSTEM_MUSIC_ONOFF, //0X19
    DEV_CONF_SYSTEM_FW, //0x1A
    DEV_CONF_SYSTEM_GSM_MODLUE,

    // Button

    DEV_CONF_BUTTONS_SOS = 0X20,
    DEV_CONF_BUTTONS_CALL_1,
    DEV_CONF_BUTTONS_CALL_2,


    // Phone
    DEV_CONF_PHONE_AUTH_NUM = 0x30,
    DEV_CONF_PHONE_SMS_PREFIX,
    DEV_CONF_PHONE_SOS_OPTION,
    DEV_CONF_PHONE_SWITCHES,

    // GPRS 0x40
    DEV_CONF_GPRS_APN = 0x40,
    DEV_CONF_GPRS_APN_USER_NAME,
    DEV_CONF_GPRS_APN_PASSWORD,
    DEV_CONF_GPRS_SERVER_PARAM,
    DEV_CONF_GPRS_INTERVAL,
    DEV_CONF_GPRS_CINTINUE_LOC,
    DEV_CONF_GPRS_HEART_RATE, //0X46
    DEV_CONF_GPRS_USER_ID,


    // ALERT 0x29
    DEV_CONF_ALERT_POWER = 0x50,
    DEV_CONF_ALERT_GEO, //0x51
    DEV_CONF_ALERT_MOTION,  //0x52
    DEV_CONF_ALERT_NO_MOTION,  //0x53
    DEV_CONF_ALERT_OVER_SPEED,  //0x54
    DEV_CONF_ALERT_TILT,   //0x55
    DEV_CONF_ALERT_FALLDOWN, //0x56

    DEV_CONF_BLE_SCAN_TIME = 0X70,
    DEV_CONF_BLE_SCAN_BEACON_TIME , 
    DEV_CONF_BLE_BEACON_UUID , 

    DEV_CONF_READ_SETTINGS = 0xF0,
    DEV_CONF_READ_FACTORY_SETTING = 0xF1,

}DEV_CONF_PB_ENUM;

#pragma pack(1)


typedef struct {
    uint32_t moduleNumber;
}DevConfSys_MoudleNum_t;


#pragma pack()






#endif

