


// This label is used for trace who malloc heap
#ifndef __LIB_HEAP_LABEL_H
#define __LIB_HEAP_LABEL_H

enum
{
    PROTO_READ_CONFIG_SETTING 		= 0x01,
    PROTO_PACK_DATA_PACK,
    PROTO_PACK_SEND_MSG_PACK,
    PROTO_PACK_RESP_HISTORICAL_DATA,
    PROTO_PACK_SEND_HISTORICAL_DATA,
    PROTO_PACK_MEMORY_READER,

    GSM_EPB_RECV_DATA_BUFF, //7
    SMSP_START_FOR_SOURCE_NUMBER,
    SMSP_START_FOR_RESP_TEXT,
    SMSP_ALERT_TEXT,

    TCPIP_RECV_REQUEST_PAYLOAD, //11
    TCPIP_RECV_SERVER_ADDR_PARSED,

    TFS_COPY_DATA_TO_SAVE, //13
    BLE_TEMP_LOG_BUFFER,

    DFU_REQ_INIT_COMMAND, //15
    DFU_SAVE_SETTING_BUFFER,
    DFU_WRITE_FLASH_TEXT,

    NUS_EPB_RECV_DATA_BUFF, //18

    
    HID_EPB_SEND_DATA_BUFF,

};


#endif
